name: mycleanspace
recipe: wordpress
config:
  php: 8.2
  composer_version: 2
  webroot: .
  database: mysql
  cache: redis
  ssl: false
  via: nginx
  xdebug: true
services:
  appserver:
    build:
      - cp wp-config-local.php wp-config.php
    run:
      - .lando/run.sh